install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_macOS-64bit.tar.gz
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rm -rf public
script:
  - hugo
branches:
 only:
 - master
